services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME:-mypostgrescontainer}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-event-sourcing
    restart: always
    ports:
      - "2025:1025"   # SMTP
      - "8125:8025"   # Web UI
  
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.2
    container_name: aspire-dashboard
    platform: linux/amd64
    ports:
      - "18888:18888"    # Main dashboard UI port
      - "4317:18889"     # OTLP ingestion port
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true   # Allows access without authentication
    restart: unless-stopped
    
volumes:
  postgres_data: